### PR TITLE
[Docs] Update CHANGES.md for v1.1.1 release

### PR DESCRIPTION
**Pull request by foundrytom**
Prep for release including https://github.com/TheFoundryVisionmongers/fn-pylint-action/security/dependabot/1

### CODE REVIEW

**Comment by foundrytom** [comment]
@feltech there is a check run specifically targeting the `v1.1.1-beta.1` tag here: https://github.com/foundrytom/OpenAssetIO/runs/6485341736?check_suite_focus=true#step:6:1

**Review by feltech — APPROVED** [review]

**Review by feltech — CHANGES_REQUESTED** [review]
[fix] package(-lock).json also needs updating

**Comment by foundrytom** [comment]
> [fix] package(-lock).json also needs updating

This is already updated here: https://github.com/TheFoundryVisionmongers/fn-pylint-action/commit/2fd303ff9fe149073f68e24e9ccd098f0228e041

**Comment by feltech** [comment]
> > [fix] package(-lock).json also needs updating
> 
> This is already updated here: [2fd303f](https://github.com/TheFoundryVisionmongers/fn-pylint-action/commit/2fd303ff9fe149073f68e24e9ccd098f0228e041)

Apologies, I shouldn't have put the `(-lock)` in there.  Presumably we still need to keep `package.json` up to date manually?

**Comment by foundrytom** [comment]
> > > [fix] package(-lock).json also needs updating
> > 
> > 
> > This is already updated here: [2fd303f](https://github.com/TheFoundryVisionmongers/fn-pylint-action/commit/2fd303ff9fe149073f68e24e9ccd098f0228e041)
> 
> Apologies, I shouldn't have put the `(-lock)` in there. Presumably we still need to keep `package.json` up to date manually?



OOOH sorry, do yo mean the project package version not `node-fetch`? 🙃 was looking at the other version update....

**Comment by foundrytom** [comment]
> > > > [fix] package(-lock).json also needs updating

@feltech Brain functioning now, updated [here](https://github.com/TheFoundryVisionmongers/fn-pylint-action/pull/6/commits/73831432dbb72dbe85cadeb51b52c1066c0c7de5).

**Review by feltech — APPROVED** [review]
LGTM rebase, squash and merge when ready.

**Pull request merged**
